module.exports = {
    "codReqVacio": "11",
    "codReqIncom": "11",
    "codClienteNoExiste": "13",
    "codProgramaNoExiste": "14",
    "codTokenAccesoNoValido": "12",
    "codNoDatos": "15",
    "codNoExisteComercio": "16",
    "codTransaccionError": "10",
    "codContratoNoRegistrado": "17",
    "codTokenContratoNoValido": "17",
    "codMontoMayorAlContrato": "20",
    "codIdOriginalRepite": "19",
    "codReferenciaExternoNoValido": "11",
    "codFlujoNoValido": "11",
    "codMontoMenorACero": "11",
    "codNoEncuentraIdOri": "11",
    "codFechaFueraLimite": "20",
    "codPorcentajeDisponibilidadCero" : "21",
    "codLimitePrestamoPorPrograma" : "22",
    "codFechaNoCoherente" : "23",
    "codProcesoCierre" : "24",
    "codProcesoCierreErr" : "25",
    "codIdOriginalNoExiste" : "26",
    "codReqInvalido":"11",
    "codServNoDisponible":"28",
    "codTipoDocumentoNoValido":"29",
    "codExportarArchivo":"30"
}